#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process
# You must use kill.


# Get the program pid
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
	kill -15 "$id"
fi

